name: time_tracker_client
description: Client for service for tracking the time your team spent on different projects

version: 0.0.1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  auto_route: ^4.0.1
  injectable: ^1.5.3
  get_it: ^7.2.0

  shared_preferences: ^2.0.15
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1

  dio: ^4.0.6
  retrofit: ^3.0.1+1
  jwt_decoder: ^2.0.1
  google_fonts: ^3.0.1
  json_annotation: ^4.5.0

  intl: ^0.17.0
  horizontal_data_table: ^4.1.1+1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  auto_route_generator: any
  injectable_generator: any
  json_serializable: any
  retrofit_generator: any
  build_runner: any

flutter:
  uses-material-design: true
